"""
generate_synthetic_data.py
Project: Public Health Surveillance Data Pipeline
Author: Aly Drame, MD, MPH, MBA

IMPORTANT: All data generated by this script are entirely synthetic.
No real patient records, no CDC surveillance data, no state health
department data, and no personally identifiable information are
included. Statistical distributions are informed by publicly available
CDC surveillance guidance and academic literature only.

This script generates four related tables:
  1. cases.csv         — core case investigation records
  2. lab_results.csv   — laboratory test results per case
  3. contacts.csv      — contact tracing records
  4. jurisdictions.csv — jurisdiction reference table
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
import os

np.random.seed(42)
random.seed(42)

os.makedirs('data/raw',       exist_ok=True)
os.makedirs('data/processed', exist_ok=True)
os.makedirs('outputs',        exist_ok=True)

# ══════════════════════════════════════════════════════════════════
# REFERENCE DATA
# ══════════════════════════════════════════════════════════════════

DISEASE_MAP = {
    'COV': 'COVID-19',
    'INF': 'Influenza',
    'MEA': 'Measles',
    'HEP': 'Hepatitis A',
    'SAL': 'Salmonellosis',
    'MPX': 'Mpox',
    'TUB': 'Tuberculosis',
    'PER': 'Pertussis',
    'VAR': 'Varicella',
    'MEN': 'Meningococcal Disease'
}

# Disease weights mirror approximate NNDSS case counts proportions
DISEASE_WEIGHTS = [0.35, 0.25, 0.05, 0.07, 0.08,
                   0.06, 0.05, 0.04, 0.03, 0.02]

JURISDICTIONS = {
    'GA': ('Georgia',           'Region 4',  10912876, 'Mixed',                'Medium'),
    'FL': ('Florida',           'Region 4',  22244823, 'Predominantly Urban',  'High'),
    'TX': ('Texas',             'Region 6',  30029572, 'Mixed',                'High'),
    'NY': ('New York',          'Region 2',  20201249, 'Predominantly Urban',  'High'),
    'CA': ('California',        'Region 9',  39538223, 'Predominantly Urban',  'High'),
    'OH': ('Ohio',              'Region 5',  11799448, 'Mixed',                'Medium'),
    'PA': ('Pennsylvania',      'Region 3',  13002700, 'Mixed',                'Medium'),
    'IL': ('Illinois',          'Region 5',  12671821, 'Mixed',                'Medium'),
    'NC': ('North Carolina',    'Region 4',  10439388, 'Mixed',                'Medium'),
    'AZ': ('Arizona',           'Region 9',   7151502, 'Mixed',                'Medium'),
    'MI': ('Michigan',          'Region 5',  10077331, 'Mixed',                'Medium'),
    'WA': ('Washington',        'Region 10',  7705281, 'Predominantly Urban',  'High'),
    'CO': ('Colorado',          'Region 8',   5773714, 'Predominantly Urban',  'Medium'),
    'MN': ('Minnesota',         'Region 5',   5706494, 'Mixed',                'Medium'),
    'TN': ('Tennessee',         'Region 4',   6910840, 'Mixed',                'Low'),
}

# ══════════════════════════════════════════════════════════════════
# TABLE 4 — JURISDICTIONS (build first as reference)
# ══════════════════════════════════════════════════════════════════

jur_rows = []
for jid, (name, region, pop, urban, capacity) in JURISDICTIONS.items():
    jur_rows.append({
        'jurisdiction_id':            jid,
        'jurisdiction_name':          name,
        'region':                     region,
        'population_2022':            pop,
        'urban_rural_class':          urban,
        'health_department_capacity': capacity
    })

jurisdictions_df = pd.DataFrame(jur_rows)
jurisdictions_df.to_csv('data/raw/jurisdictions.csv', index=False)
print(f"[JURISDICTIONS] {len(jurisdictions_df)} rows saved")

# ══════════════════════════════════════════════════════════════════
# TABLE 1 — CASES
# ══════════════════════════════════════════════════════════════════

N_CASES = 10_000

OBS_START = datetime(2022, 1, 1)
OBS_END   = datetime(2024, 12, 31)

def rand_date(start: datetime, end: datetime) -> str:
    return (start + timedelta(
        days=random.randint(0, (end - start).days)
    )).strftime('%Y-%m-%d')

def maybe_null(value, prob_missing: float):
    """Return None with probability prob_missing, else value."""
    return None if random.random() < prob_missing else value

# Draw disease codes
disease_codes = np.random.choice(
    list(DISEASE_MAP.keys()), N_CASES, p=DISEASE_WEIGHTS)

# Generate report dates
report_dates = [
    OBS_START + timedelta(days=random.randint(0, (OBS_END-OBS_START).days))
    for _ in range(N_CASES)
]

# Onset date: typically 1–14 days before report date
onset_offsets = np.random.randint(-14, 1, N_CASES)

# Age
age_years_raw = np.random.choice(
    list(range(0, 100)),
    N_CASES,
    p=[max(0.001, 0.01 - abs(i - 35) * 0.0002) for i in range(100)]
)
age_years_raw = np.clip(age_years_raw, 0, 99)

def age_to_group(age):
    if age is None:
        return None
    if age <= 4:   return '0-4'
    if age <= 17:  return '5-17'
    if age <= 49:  return '18-49'
    if age <= 64:  return '50-64'
    return '65+'

REPORT_SOURCES   = ['Electronic Lab Report','Provider Report',
                    'Hospital Report','Death Certificate',
                    'Contact Tracing','Unknown']
SOURCE_WEIGHTS   = [0.45, 0.25, 0.15, 0.05, 0.07, 0.03]

CASE_STATUSES    = ['Confirmed','Probable','Suspect']
STATUS_WEIGHTS   = [0.70, 0.20, 0.10]

INV_STATUSES     = ['Complete','Closed','In Progress',
                    'Open','Unable to Complete']
INV_WEIGHTS      = [0.45, 0.25, 0.15, 0.10, 0.05]

DATA_SOURCES     = ['DCIPHER','ELR','Manual Entry','ESSENCE']
DS_WEIGHTS       = [0.40, 0.35, 0.15, 0.10]

RACE_ETH         = ['NH White','NH Black','Hispanic','NH Asian',
                    'NH AIAN','NH NHPI','Unknown']
RACE_WEIGHTS     = [0.40, 0.18, 0.20, 0.07, 0.02, 0.01, 0.12]

jur_list = list(JURISDICTIONS.keys())

case_rows = []
for i in range(N_CASES):
    rdate  = report_dates[i]
    odate  = rdate + timedelta(days=int(onset_offsets[i]))
    if odate < OBS_START:
        odate = OBS_START

    age    = int(age_years_raw[i])
    inv_st = np.random.choice(INV_STATUSES, p=INV_WEIGHTS)

    # Close date only for completed/closed investigations
    if inv_st in ('Complete','Closed'):
        close_offset = np.random.randint(1, 45)
        cdate  = rdate + timedelta(days=close_offset)
        if cdate > OBS_END:
            cdate = OBS_END
        days_to_close = (cdate - rdate).days
        close_date_str = cdate.strftime('%Y-%m-%d')
    else:
        close_date_str = None
        days_to_close  = None

    # Clinical severity — disease-specific probabilities
    disease = disease_codes[i]
    hosp_prob = {'COV':0.18,'INF':0.08,'MEA':0.15,'HEP':0.12,
                 'SAL':0.10,'MPX':0.05,'TUB':0.25,'PER':0.07,
                 'VAR':0.04,'MEN':0.55}.get(disease, 0.10)
    hosp = 'Y' if random.random() < hosp_prob else 'N'

    icu_prob = 0.25 if hosp == 'Y' else 0.01
    icu  = 'Y' if random.random() < icu_prob else 'N'

    died_prob = 0.05 if hosp == 'Y' else 0.001
    died = 'Y' if random.random() < died_prob else 'N'

    # Completeness score — percent of key fields populated
    key_fields = [
        disease, rdate, odate, age, 'sex',
        hosp, inv_st, close_date_str
    ]
    completeness = round(
        sum(1 for f in key_fields if f is not None) /
        len(key_fields) * 100, 1)

    case_rows.append({
        'case_id':              f'CASE-{str(i+1).zfill(7)}',
        'disease_code':         disease,
        'disease_name':         DISEASE_MAP[disease],
        'report_date':          maybe_null(rdate.strftime('%Y-%m-%d'), 0.02),
        'onset_date':           maybe_null(odate.strftime('%Y-%m-%d'), 0.12),
        'report_source':        np.random.choice(REPORT_SOURCES,
                                                  p=SOURCE_WEIGHTS),
        'jurisdiction_id':      np.random.choice(jur_list),
        'age_years':            maybe_null(age, 0.06),
        'age_group':            maybe_null(age_to_group(age), 0.06),
        'sex':                  maybe_null(
                                    np.random.choice(['M','F','U'],
                                                      p=[0.48,0.48,0.04]),
                                    0.04),
        'race_ethnicity':       maybe_null(
                                    np.random.choice(RACE_ETH,
                                                      p=RACE_WEIGHTS),
                                    0.15),
        'hospitalized':         maybe_null(hosp, 0.08),
        'icu_admission':        maybe_null(icu, 0.10),
        'died':                 maybe_null(died, 0.05),
        'case_status':          np.random.choice(CASE_STATUSES,
                                                  p=STATUS_WEIGHTS),
        'investigation_status': inv_st,
        'close_date':           close_date_str,
        'days_to_close':        days_to_close,
        'imported_flag':        maybe_null(
                                    'Y' if random.random() < 0.08 else 'N',
                                    0.05),
        'outbreak_associated':  maybe_null(
                                    'Y' if random.random() < 0.12 else 'N',
                                    0.08),
        'data_source':          np.random.choice(DATA_SOURCES,
                                                  p=DS_WEIGHTS),
        'completeness_score':   completeness,
    })

cases_df = pd.DataFrame(case_rows)

# Introduce ~1% intentional duplicates to test deduplication logic
n_dupes = int(N_CASES * 0.01)
dup_rows = cases_df.sample(n=n_dupes, random_state=99).copy()
# Slightly alter the case_id to simulate near-duplicates
dup_rows['case_id'] = dup_rows['case_id'] + '-DUP'
cases_df = pd.concat([cases_df, dup_rows], ignore_index=True)

cases_df.to_csv('data/raw/cases_raw.csv', index=False)
print(f"[CASES] {len(cases_df):,} rows saved "
      f"({n_dupes} intentional duplicates included)")

# ══════════════════════════════════════════════════════════════════
# TABLE 2 — LAB RESULTS
# Approximately 70% of cases have at least one lab result.
# ══════════════════════════════════════════════════════════════════

# Only generate for original cases (not duplicates)
original_cases = cases_df[~cases_df['case_id'].str.endswith('-DUP')]

SPECIMEN_MAP = {
    'COV': ['Nasopharyngeal Swab','Saliva'],
    'INF': ['Nasopharyngeal Swab','Throat Swab'],
    'MEA': ['Nasopharyngeal Swab','Serum'],
    'HEP': ['Blood','Serum'],
    'SAL': ['Stool'],
    'MPX': ['Lesion Swab','Blood'],
    'TUB': ['Sputum','Blood'],
    'PER': ['Nasopharyngeal Swab'],
    'VAR': ['Lesion Swab','Blood'],
    'MEN': ['CSF','Blood'],
}

TEST_MAP = {
    'COV': ['PCR','Rapid Antigen'],
    'INF': ['PCR','Rapid Antigen'],
    'MEA': ['PCR','Serology'],
    'HEP': ['Serology'],
    'SAL': ['Culture'],
    'MPX': ['PCR','Whole Genome Sequencing'],
    'TUB': ['Culture','PCR'],
    'PER': ['PCR','Culture'],
    'VAR': ['PCR','Serology'],
    'MEN': ['Culture','PCR'],
}

LAB_NAMES = ['State Public Health Lab','Commercial Lab',
             'Hospital Lab','CDC Lab']
LAB_WEIGHTS = [0.30, 0.45, 0.20, 0.05]

lab_rows = []
lab_counter = 1

for _, case in original_cases.iterrows():
    if random.random() > 0.70:
        continue   # 30% of cases have no lab result

    n_tests = np.random.choice([1, 2, 3], p=[0.70, 0.20, 0.10])
    disease = case['disease_code']
    specimens = SPECIMEN_MAP.get(disease, ['Blood'])
    tests     = TEST_MAP.get(disease, ['PCR'])

    for _ in range(n_tests):
        cdate_str = case['report_date']
        if cdate_str:
            cdate  = datetime.strptime(cdate_str, '%Y-%m-%d')
            col_dt = cdate - timedelta(days=random.randint(0, 3))
            res_dt = col_dt + timedelta(days=random.randint(0, 7))
            col_str = maybe_null(col_dt.strftime('%Y-%m-%d'), 0.05)
            res_str = maybe_null(res_dt.strftime('%Y-%m-%d'), 0.03)
            d2r = (res_dt - col_dt).days if col_str and res_str else None
        else:
            col_str = res_str = d2r = None

        result = np.random.choice(
            ['Positive','Negative','Indeterminate','Pending'],
            p=[0.60, 0.28, 0.07, 0.05])

        pathogen = (DISEASE_MAP.get(disease,'Unknown')
                    if result == 'Positive' else None)

        lab_rows.append({
            'lab_id':           f'LAB-{str(lab_counter).zfill(7)}',
            'case_id':          case['case_id'],
            'specimen_type':    random.choice(specimens),
            'collection_date':  col_str,
            'result_date':      res_str,
            'test_type':        random.choice(tests),
            'result':           result,
            'pathogen_detected': pathogen,
            'lab_name':         np.random.choice(LAB_NAMES, p=LAB_WEIGHTS),
            'days_to_result':   d2r,
        })
        lab_counter += 1

lab_df = pd.DataFrame(lab_rows)
lab_df.to_csv('data/raw/lab_results_raw.csv', index=False)
print(f"[LAB RESULTS] {len(lab_df):,} rows saved")

# ══════════════════════════════════════════════════════════════════
# TABLE 3 — CONTACTS
# Contact tracing data for cases where investigation is complete.
# High-transmission diseases have more contacts identified.
# ══════════════════════════════════════════════════════════════════

HIGH_TRANSMISSION = {'COV','MEA','PER','VAR','INF'}

EXPOSURE_SETTINGS = ['Household','Healthcare','School',
                     'Workplace','Community','Unknown']
EXP_WEIGHTS       = [0.40, 0.15, 0.10, 0.15, 0.15, 0.05]

CONTACT_STATUSES  = ['Completed','Under Monitoring',
                     'Identified','Lost to Follow-up']
CS_WEIGHTS        = [0.55, 0.20, 0.15, 0.10]

contact_rows = []
con_counter  = 1

closed_cases = original_cases[
    original_cases['investigation_status'].isin(['Complete','Closed'])
]

for _, case in closed_cases.iterrows():
    disease = case['disease_code']
    if disease in HIGH_TRANSMISSION:
        n_contacts = np.random.poisson(4.5)
    else:
        n_contacts = np.random.poisson(1.5)

    for _ in range(n_contacts):
        cdate_str = case['report_date']
        if cdate_str:
            cdate     = datetime.strptime(cdate_str, '%Y-%m-%d')
            con_dt    = cdate + timedelta(days=random.randint(0, 7))
            con_str   = con_dt.strftime('%Y-%m-%d')
        else:
            con_str   = None

        contact_rows.append({
            'contact_id':       f'CON-{str(con_counter).zfill(7)}',
            'case_id':          case['case_id'],
            'contact_date':     con_str,
            'exposure_setting': maybe_null(
                                    np.random.choice(EXPOSURE_SETTINGS,
                                                      p=EXP_WEIGHTS),
                                    0.10),
            'contact_status':   np.random.choice(CONTACT_STATUSES,
                                                  p=CS_WEIGHTS),
            'became_case':      maybe_null(
                                    'Y' if random.random() < 0.12 else 'N',
                                    0.12),
            'days_monitored':   maybe_null(
                                    np.random.randint(0, 22), 0.08),
        })
        con_counter += 1

contacts_df = pd.DataFrame(contact_rows)
contacts_df.to_csv('data/raw/contacts_raw.csv', index=False)
print(f"[CONTACTS] {len(contacts_df):,} rows saved")

# ══════════════════════════════════════════════════════════════════
# SUMMARY
# ══════════════════════════════════════════════════════════════════

print("\n=== DATASET GENERATION COMPLETE ===")
print(f"cases_raw.csv         : {len(cases_df):,} rows")
print(f"lab_results_raw.csv   : {len(lab_df):,} rows")
print(f"contacts_raw.csv      : {len(contacts_df):,} rows")
print(f"jurisdictions.csv     : {len(jurisdictions_df):,} rows")

print("\n--- Disease distribution ---")
print(cases_df['disease_name'].value_counts().to_string())

print("\n--- Missing value rates (cases) ---")
miss = cases_df.isnull().mean().mul(100).round(1)
print(miss[miss > 0].to_string())

print("\nAll raw files saved to data/raw/")
